In [54]:
import json
from pathlib import Path

import pandas as pd
import biopsykit as bp
from fau_colors import cmaps, register_fausans_font

import matplotlib.pyplot as plt
import seaborn as sns

from empkins_io.datasets.d03.micro_gapvii import MicroBaseDataset, MicroEcgDataset

%load_ext autoreload
%autoreload 2
%matplotlib widget

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [55]:
register_fausans_font()
plt.close("all")

palette = sns.color_palette(cmaps.faculties)
sns.set_theme(context="notebook", style="ticks", font="sans-serif", palette=palette)

plt.rcParams["figure.figsize"] = (10, 5)
plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["mathtext.default"] = "regular"

palette

[(0.0, 0.1843137254901961, 0.4235294117647059),
 (0.4666666666666667, 0.6235294117647059, 0.7098039215686275),
 (1.0, 0.7215686274509804, 0.10980392156862745),
 (0.0, 0.6392156862745098, 0.8784313725490196),
 (0.2627450980392157, 0.6901960784313725, 0.16470588235294117),
 (0.7843137254901961, 0.06274509803921569, 0.1803921568627451)]

In [56]:
deploy_type = "local"

config_dict = json.load(Path("../config.json").open(encoding="utf-8"))

base_path = Path(config_dict[deploy_type]["base_path"])
base_path

PosixPath('/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro')

In [57]:
dataset = MicroEcgDataset(base_path, phase_fine=False, exclude_missing_data=False, use_cache=True)
dataset

MicroEcgDataset [1060 groups/rows]

        subject condition     phase
   0     VP_001      tsst  Baseline
   1     VP_001      tsst      Prep
   2     VP_001      tsst      Talk
   3     VP_001      tsst      Math
   4     VP_001      tsst  Recovery
   ...      ...       ...       ...
   1055  VP_110     ftsst  Baseline
   1056  VP_110     ftsst      Prep
   1057  VP_110     ftsst      Talk
   1058  VP_110     ftsst      Math
   1059  VP_110     ftsst  Recovery

   [1060 rows x 3 columns]

In [53]:
dataset_test = MicroBaseDataset(base_path, phase_fine=False, exclude_missing_data=False, use_cache=False)
dataset_test._get_nilspod_data("VP_101", "ftsst", None)

/Users/abelluc/Code/empkins-d03-preprocessing/.venv/lib/python3.9/site-packages/nilspodlib/legacy.py:252: CorruptedPackageWarning: Number of bytes in binary data does not match sample size indicated by header. This can be caused by a bug affecting all synchronised sessions recorded with firmware versions before 0.14.0.
  warnings.warn(

                                      3d73                                \
                                     gyr_x     gyr_y     gyr_z     acc_x
time
2023-11-22 14:11:46.031250+01:00 -0.061035  0.610352  0.000000  0.091011
2023-11-22 14:11:46.035156+01:00 -0.183105  0.610352  0.000000  0.114961
2023-11-22 14:11:46.039062+01:00 -0.122070  0.671387 -0.061035  0.081431
2023-11-22 14:11:46.042968+01:00 -0.122070  0.671387  0.000000  0.071851
2023-11-22 14:11:46.046875+01:00 -0.183105  0.671387  0.122070  0.062271
...                                    ...       ...       ...       ...
2023-11-22 16:33:44.210937+01:00  0.000000  0.488281  0.061035 -0.043110
2023-11-22 16:33:44.214843+01:00  0.000000  0.549316  0.000000 -0.038320
2023-11-22 16:33:44.218750+01:00 -0.061035  0.549316 -0.061035 -0.071851
2023-11-22 16:33:44.222656+01:00 -0.061035  0.488281 -0.061035 -0.086221
2023-11-22 16:33:44.226562+01:00  0.000000  0.488281 -0.061035 -0.043110

                                                          9e02            \
                                     acc_y     acc_z     gyr_x     gyr_y
time
2023-11-22 14:11:46.031250+01:00  0.354463  9.747729  0.488281 -0.610352
2023-11-22 14:11:46.035156+01:00  0.359253  9.747729  0.488281 -0.671387
2023-11-22 14:11:46.039062+01:00  0.349673  9.757310  0.427246 -0.671387
2023-11-22 14:11:46.042968+01:00  0.325723  9.714199  0.427246 -0.671387
2023-11-22 14:11:46.046875+01:00  0.335303  9.709409  0.427246 -0.610352
...                                    ...       ...       ...       ...
2023-11-22 16:33:44.210937+01:00 -9.632769 -0.239502  0.366211 -0.793457
2023-11-22 16:33:44.214843+01:00 -9.627979 -0.258662  0.366211 -0.610352
2023-11-22 16:33:44.218750+01:00 -9.671089 -0.234712  0.305176 -0.488281
2023-11-22 16:33:44.222656+01:00 -9.675879 -0.239502  0.366211 -0.610352
2023-11-22 16:33:44.226562+01:00 -9.647139 -0.229922  0.366211 -0.610352

                                                     ...                    \
                                     gyr_z    acc_x  ... analog_0 analog_1
time                                                 ...
2023-11-22 14:11:46.031250+01:00 -0.061035  0.05269  ...    214.0    167.0
2023-11-22 14:11:46.035156+01:00 -0.061035  0.04311  ...    255.0    167.0
2023-11-22 14:11:46.039062+01:00  0.183105  0.03353  ...    174.0    167.0
2023-11-22 14:11:46.042968+01:00  0.061035  0.03353  ...     60.0    168.0
2023-11-22 14:11:46.046875+01:00  0.000000  0.02395  ...     97.0    167.0
...                                    ...      ...  ...      ...      ...
2023-11-22 16:33:44.210937+01:00  0.122070  0.05269  ...     59.0      9.0
2023-11-22 16:33:44.214843+01:00  0.183105  0.02874  ...    136.0      9.0
2023-11-22 16:33:44.218750+01:00  0.061035  0.01437  ...    255.0      9.0
2023-11-22 16:33:44.222656+01:00 -0.061035  0.02874  ...    253.0      8.0
2023-11-22 16:33:44.226562+01:00  0.061035  0.04311  ...    153.0      8.0

                                               b0c2                      \
                                 analog_2     gyr_x     gyr_y     gyr_z
time
2023-11-22 14:11:46.031250+01:00    254.0  0.610352 -0.427246 -0.122070
2023-11-22 14:11:46.035156+01:00    245.0  0.488281 -0.427246 -0.122070
2023-11-22 14:11:46.039062+01:00    104.0  0.244141 -0.427246 -0.061035
2023-11-22 14:11:46.042968+01:00     36.0  0.183105 -0.427246 -0.061035
2023-11-22 14:11:46.046875+01:00     73.0  0.122070 -0.427246 -0.122070
...                                   ...       ...       ...       ...
2023-11-22 16:33:44.210937+01:00      0.0  3.356934 -0.549316 -2.624512
2023-11-22 16:33:44.214843+01:00     79.0  3.417969 -0.183105 -2.624512
2023-11-22 16:33:44.218750+01:00    204.0  3.417969  0.000000 -2.624512
2023-11-22 16:33:44.222656+01:00    180.0  3.112793  0.549316 -2.502441
2023-11-22 16:33:44.226562+01:00      0.0  2.685547  1.159668 -2.197266


                                     acc_x     acc_y     acc_z   ecg
time
2023-11-22 14:11:46.031250+01:00  0.598755 -9.307046  3.353027   0.0
2023-11-22 14:11:46.035156+01:00  0.598755 -9.311836  3.357817  -1.0
2023-11-22 14:11:46.039062+01:00  0.603545 -9.311836  3.367397  -3.0
2023-11-22 14:11:46.042968+01:00  0.617915 -9.321416  3.362607  -3.0
2023-11-22 14:11:46.046875+01:00  0.622705 -9.330996  3.362607  -4.0
...                                    ...       ...       ...   ...
2023-11-22 16:33:44.210937+01:00 -0.833467 -9.671089 -0.296982 -40.0
2023-11-22 16:33:44.214843+01:00 -0.833467 -9.647139 -0.119751 -53.0
2023-11-22 16:33:44.218750+01:00 -0.823887 -9.637559 -0.019160 -66.0
2023-11-22 16:33:44.222656+01:00 -0.790356 -9.623188  0.191602 -77.0
2023-11-22 16:33:44.226562+01:00 -0.771196 -9.647139  0.344883 -84.0

[2180659 rows x 22 columns]

In [58]:
hr_results_all = pd.DataFrame()
error_dict = {}

In [60]:
for subset in dataset.groupby(["subject", "condition", "phase"]):
    
    participant = subset.index["subject"].iloc[0]
    condition = subset.index["condition"].iloc[0]
    phase = subset.index["phase"].iloc[0]

    # check if phase is pause
    if "Pause" in phase.split("_"):
        continue

    # before baseline and recovery bug fix
    #if participant not in ["VP_001", "VP_002", "VP_003", "VP_004", "VP_005", "VP_006", "VP_007", "VP_008", "VP_009", "VP_010", "VP_019", "VP_021", "VP_022", "VP_025", "VP_026", "VP_027", "VP_031", "VP_032", "VP_033", "VP_034", "VP_036", "VP_037", "VP_041", "VP_044", "VP_045", "VP_050", "VP_051", "VP_052", "VP_053", "VP_054", "VP_059", "VP_060", "VP_061", "VP_062", "VP_063", "VP_065", "VP_066", "VP_067", "VP_082", "VP_083", "VP_096", "VP_101", "VP_102", "VP_103", "VP_110"]:
    #    continue

    #if participant in ["VP_001", "VP_002", "VP_003", "VP_004", "VP_005", "VP_006", "VP_007", "VP_008", "VP_009", "VP_010"]:
    #    continue

    if hr_results_all.index.isin([(participant, condition, phase)]).any():
        continue

    print(participant, condition, phase)

    try:

        data = subset.ecg
        
        ep = bp.signals.ecg.EcgProcessor(data={"Data": data}, sampling_rate=256)
        ep.ecg_process(errors="warn")

        hr_results = ep.hrv_process(ep, "Data", index=participant, index_name="participant")
        
        hr_results["HR_Mean"] = ep.hr_result["Data"].mean()[0]
        hr_results["HR_SD"] = ep.hr_result["Data"].std()[0]
        hr_results.index = pd.MultiIndex.from_arrays([[participant], [condition], [phase]], names=("participant", "condition", "phase"))
        
        hr_results_all = pd.concat((hr_results_all, hr_results))
    except Exception as e:
        if (participant, condition) not in error_dict:
            error_dict[(participant, condition)] = e

VP_001 tsst Baseline
VP_001 tsst Prep
VP_001 tsst Talk
VP_001 tsst Math
VP_001 tsst Recovery
VP_001 ftsst Baseline
VP_001 ftsst Prep
VP_001 ftsst Talk
VP_001 ftsst Math
VP_001 ftsst Recovery
VP_002 tsst Baseline
VP_002 tsst Prep
VP_002 tsst Talk
VP_002 tsst Math
VP_002 tsst Recovery
VP_002 ftsst Baseline
VP_002 ftsst Prep
VP_002 ftsst Talk
VP_002 ftsst Math
VP_002 ftsst Recovery
VP_003 tsst Baseline
VP_003 tsst Prep
VP_003 tsst Talk
VP_003 tsst Math
VP_003 tsst Recovery
VP_003 ftsst Baseline
VP_003 ftsst Prep
VP_003 ftsst Talk
VP_003 ftsst Math
VP_003 ftsst Recovery
VP_004 tsst Baseline
VP_004 tsst Prep
VP_004 tsst Talk
VP_004 tsst Math
VP_004 tsst Recovery
VP_004 ftsst Baseline
VP_004 ftsst Prep
VP_004 ftsst Talk
VP_004 ftsst Math
VP_004 ftsst Recovery
VP_005 tsst Baseline
VP_005 tsst Prep
VP_005 tsst Talk
VP_005 tsst Math
VP_005 tsst Recovery
VP_005 ftsst Baseline
VP_005 ftsst Prep
VP_005 ftsst Talk
VP_005 ftsst Math
VP_005 ftsst Recovery
VP_006 tsst Baseline
VP_006 tsst Prep
VP_006 tsst Talk
VP_006 tsst Math
VP_006 tsst Recovery
VP_006 ftsst Baseline
VP_006 ftsst Prep
VP_006 ftsst Talk
VP_006 ftsst Math
VP_006 ftsst Recovery
VP_007 tsst Baseline
VP_007 tsst Prep
VP_007 tsst Talk
VP_007 tsst Math
VP_007 tsst Recovery
VP_007 ftsst Baseline
VP_007 ftsst Prep
VP_007 ftsst Talk
VP_007 ftsst Math
VP_007 ftsst Recovery
VP_008 tsst Baseline
VP_008 tsst Prep
VP_008 tsst Talk
VP_008 tsst Math
VP_008 tsst Recovery
VP_008 ftsst Baseline
VP_008 ftsst Prep
VP_008 ftsst Talk
VP_008 ftsst Math
VP_008 ftsst Recovery
VP_009 tsst Baseline
VP_009 tsst Prep
VP_009 tsst Talk
VP_009 tsst Math
VP_009 tsst Recovery
VP_010 tsst Baseline
VP_010 tsst Prep
VP_010 tsst Talk
VP_010 tsst Math
VP_010 tsst Recovery
VP_014 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_021 tsst Baseline
VP_021 tsst Prep
VP_021 tsst Talk
VP_021 tsst Math
VP_021 tsst Recovery
VP_022 tsst Baseline
VP_022 tsst Prep
VP_022 tsst Talk
VP_022 tsst Math
VP_022 tsst Recovery
VP_022 ftsst Baseline
VP_022 ftsst Prep
VP_022 ftsst Talk
VP_022 ftsst Math
VP_022 ftsst Recovery
VP_025 tsst Baseline
VP_025 tsst Prep
VP_025 tsst Talk
VP_025 tsst Math
VP_025 tsst Recovery
VP_025 ftsst Baseline
VP_025 ftsst Prep
VP_025 ftsst Talk
VP_025 ftsst Math
VP_025 ftsst Recovery
VP_026 tsst Baseline
VP_026 tsst Prep
VP_026 tsst Talk
VP_026 tsst Math
VP_026 tsst Recovery
VP_026 ftsst Baseline
VP_026 ftsst Prep
VP_026 ftsst Talk
VP_026 ftsst Math
VP_026 ftsst Recovery
VP_027 tsst Baseline
VP_027 tsst Prep
VP_027 tsst Talk
VP_027 tsst Math
VP_027 tsst Recovery
VP_027 ftsst Baseline
VP_027 ftsst Prep
VP_027 ftsst Talk
VP_027 ftsst Math
VP_027 ftsst Recovery
VP_031 tsst Baseline
VP_031 tsst Prep
VP_031 tsst Talk
VP_031 tsst Math
VP_031 tsst Recovery
VP_031 ftsst Baseline
VP_031 ftsst Prep
VP_031 ftsst Talk
VP_031 ftsst Math
VP_031 ftsst Recovery
VP_032 tsst Baseline
VP_032 tsst Prep
VP_032 tsst Talk
VP_032 tsst Math
VP_032 tsst Recovery
VP_032 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_032 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_032 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_032 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_032 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 tsst Baseline
VP_033 tsst Prep
VP_033 tsst Talk
VP_033 tsst Math
VP_033 tsst Recovery
VP_033 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_033 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_044 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_044 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_044 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_044 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_044 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_045 tsst Baseline
VP_045 tsst Prep
VP_045 tsst Talk
VP_045 tsst Math
VP_045 tsst Recovery
VP_045 ftsst Baseline
VP_045 ftsst Prep
VP_045 ftsst Talk
VP_045 ftsst Math
VP_045 ftsst Recovery
VP_050 tsst Baseline
VP_050 tsst Prep
VP_050 tsst Talk
VP_050 tsst Math
VP_050 tsst Recovery
VP_051 tsst Baseline
VP_051 tsst Prep
VP_051 tsst Talk
VP_051 tsst Math
VP_051 tsst Recovery
VP_051 ftsst Baseline
VP_051 ftsst Prep
VP_051 ftsst Talk
VP_051 ftsst Math
VP_051 ftsst Recovery
VP_052 tsst Baseline
VP_052 tsst Prep
VP_052 tsst Talk
VP_052 tsst Math
VP_052 tsst Recovery
VP_053 tsst Baseline
VP_053 tsst Prep
VP_053 tsst Talk
VP_053 tsst Math
VP_053 tsst Recovery
VP_059 tsst Baseline
VP_059 tsst Prep
VP_059 tsst Talk
VP_059 tsst Math
VP_059 tsst Recovery
VP_060 tsst Baseline
VP_060 tsst Prep
VP_060 tsst Talk
VP_060 tsst Math
VP_060 tsst Recovery
VP_060 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_060 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_060 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_060 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_060 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 tsst Baseline
VP_061 tsst Prep
VP_061 tsst Talk
VP_061 tsst Math
VP_061 tsst Recovery
VP_061 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_061 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_066 ftsst Baseline
VP_066 ftsst Prep
VP_066 ftsst Talk
VP_066 ftsst Math
VP_066 ftsst Recovery
VP_067 ftsst Baseline
VP_067 ftsst Prep
VP_067 ftsst Talk
VP_067 ftsst Math
VP_067 ftsst Recovery
VP_082 ftsst Baseline
VP_082 ftsst Prep
VP_082 ftsst Talk
VP_082 ftsst Math
VP_082 ftsst Recovery
VP_083 ftsst Baseline
VP_083 ftsst Prep
VP_083 ftsst Talk
VP_083 ftsst Math
VP_083 ftsst Recovery
VP_096 tsst Baseline
VP_096 tsst Prep
VP_096 tsst Talk
VP_096 tsst Math
VP_096 tsst Recovery
VP_101 tsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 tsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 tsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 tsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_101 tsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_102 tsst Baseline
VP_102 tsst Prep
VP_102 tsst Talk
VP_102 tsst Math
VP_102 tsst Recovery
VP_103 tsst Baseline
VP_103 tsst Prep
VP_103 tsst Talk
VP_103 tsst Math
VP_103 tsst Recovery
VP_103 ftsst Baseline
VP_103 ftsst Prep
VP_103 ftsst Talk
VP_103 ftsst Math
VP_103 ftsst Recovery
VP_109 ftsst Baseline

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 ftsst Prep

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 ftsst Talk

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 ftsst Math

  0%|          | 0/1 [00:00<?, ?it/s]

VP_109 ftsst Recovery

  0%|          | 0/1 [00:00<?, ?it/s]

VP_110 tsst Baseline
VP_110 tsst Prep
VP_110 tsst Talk
VP_110 tsst Math
VP_110 tsst Recovery
VP_110 ftsst Baseline
VP_110 ftsst Prep
VP_110 ftsst Talk
VP_110 ftsst Math
VP_110 ftsst Recovery

In [ ]:
subset.nilspod

In [61]:
pd.DataFrame(error_dict, index=["error"]).T.to_csv("nilspod_errors.csv")

In [ ]:
data.plot()

In [62]:
hr_results_all

                                HRV_MeanNN   HRV_SDNN  HRV_SDANN1  HRV_SDNNI1  \
participant condition phase
VP_009      ftsst     Baseline  898.486126  66.827594   28.290076   60.847482
                      Prep      824.761285  86.299038   45.502466   75.850667
                      Talk      618.233945  53.304383   28.729384   44.693985
                      Math      600.116986  64.491980   31.328594   57.394659
                      Recovery  933.919271  75.449654   38.583202   67.011343
...                                    ...        ...         ...         ...
VP_109      ftsst     Baseline  886.972253  78.953451   51.501868   63.596989
                      Prep      864.215106  64.011666   24.833483   60.639128
                      Talk      764.242788  93.110766   52.354985   79.447680
                      Math      858.039374  65.842918   19.654141   63.352820
                      Recovery  919.687500  54.425110   20.454770   51.449747

                                HRV_SDANN2  HRV_SDNNI2  HRV_SDANN5  \
participant condition phase
VP_009      ftsst     Baseline         NaN         NaN         NaN
                      Prep             NaN         NaN         NaN
                      Talk       29.563064   46.702577         NaN
                      Math       34.042728   57.940831         NaN
                      Recovery   39.328888   66.824875         NaN
...                                    ...         ...         ...
VP_109      ftsst     Baseline   31.933327   74.774443         NaN
                      Prep             NaN         NaN         NaN
                      Talk       54.037938   82.350369         NaN
                      Math        4.078767   65.946600         NaN
                      Recovery         NaN         NaN         NaN

                                HRV_SDNNI5  HRV_RMSSD   HRV_SDSD  ...  \
participant condition phase                                       ...
VP_009      ftsst     Baseline         NaN  66.790022  66.927028  ...
                      Prep             NaN  98.185154  98.321993  ...
                      Talk             NaN  29.642852  29.669299  ...
                      Math             NaN  31.813184  31.840641  ...
                      Recovery         NaN  73.081832  73.195221  ...
...                                    ...        ...        ...  ...
VP_109      ftsst     Baseline         NaN  57.983836  58.069745  ...
                      Prep             NaN  61.219055  61.308600  ...
                      Talk             NaN  46.953804  47.005147  ...
                      Math             NaN  53.259690  53.322273  ...
                      Recovery         NaN  62.131952  62.228015  ...

                                HRV_FuzzyEn  HRV_MSEn  HRV_CMSEn  HRV_RCMSEn  \
participant condition phase
VP_009      ftsst     Baseline     1.307057  1.290359   1.354511    2.095387
                      Prep         1.537730  1.343786   1.309379    2.186214
                      Talk         0.948468  1.325866   1.280708    2.085846
                      Math         0.886150  1.559579   1.327715    2.149179
                      Recovery     1.401001  1.190378   1.387812    2.203495
...                                     ...       ...        ...         ...
VP_109      ftsst     Baseline     1.190293  1.488962   1.416344    2.068376
                      Prep         1.419649  1.436367   1.456587    2.170387
                      Talk         0.918443  1.536778   1.336290    2.207200
                      Math         1.275860  1.364689   1.383268    2.118099
                      Recovery     1.463555  1.313366   1.295966    1.963891

                                  HRV_CD   HRV_HFD   HRV_KFD   HRV_LZC  \
participant condition phase
VP_009      ftsst     Baseline  1.746561  1.898754  3.042605  0.886506
                      Prep      1.873705  1.997235  6.946891  0.919951
                      Talk      1.756819  1.755961  2.704593  0.700522
                      Math      1.688683  1.732683  2.957525  0.553156
                      Recovery  1.919939  1.929067  4.652286  0.900910
...                                  ...       ...       ...       ...
VP_109      ftsst     Baseline  1.881192  1.856165  3.842828  0.818200
                      Prep      1.863126  1.873685  4.289656  0.883948
                      Talk      1.771620  1.687977  3.092548  0.698615
                      Math      1.861438  1.785502  4.175701  0.900412
                      Recovery  1.774981  2.008497  5.285704  0.847267

                                   HR_Mean      HR_SD
participant condition phase
VP_009      ftsst     Baseline   67.158945   5.089042
                      Prep       73.564106   7.829233
                      Talk       97.787170   8.406008
                      Math      101.149631  10.975796
                      Recovery   64.678324   5.433539
...                                    ...        ...
VP_109      ftsst     Baseline   68.209942   6.402470
                      Prep       69.815752   5.306773
                      Talk       79.681072   9.717384
                      Math       70.346755   5.516417
                      Recovery   65.475178   4.013297

[774 rows x 83 columns]

In [63]:
hr_results_all.index.names = ["subject", "condition", "phase"]

In [64]:
hr_results_all_long = hr_results_all.copy()

In [74]:
hr_results_all[hr_results_all_long.groupby(["subject"]).count()["HR_Mean"] == 10]

,HRV_MeanNN_ftsst_Baseline,HRV_MeanNN_ftsst_Prep,HRV_MeanNN_ftsst_Talk,HRV_MeanNN_ftsst_Math,HRV_MeanNN_ftsst_Recovery,HRV_MeanNN_tsst_Baseline,HRV_MeanNN_tsst_Prep,HRV_MeanNN_tsst_Talk,HRV_MeanNN_tsst_Math,HRV_MeanNN_tsst_Recovery,...,HR_SD_ftsst_Baseline,HR_SD_ftsst_Prep,HR_SD_ftsst_Talk,HR_SD_ftsst_Math,HR_SD_ftsst_Recovery,HR_SD_tsst_Baseline,HR_SD_tsst_Prep,HR_SD_tsst_Talk,HR_SD_tsst_Math,HR_SD_tsst_Recovery
subject,,,,,,,,,,,,,,,,,,,,,
VP_011,824.154006,885.358364,682.090184,644.070688,900.496517,707.786396,759.093238,611.348977,595.156796,802.681872,...,5.714174,5.383550,7.789262,7.002217,5.470638,5.645469,7.024322,8.996232,7.871257,5.805243
VP_012,814.726027,717.689732,706.927190,665.844167,797.494540,753.984375,755.228062,686.560212,707.337307,776.461039,...,3.000240,5.214479,7.163562,8.267183,2.453322,3.376454,5.031209,7.687287,5.068878,3.230596
VP_013,834.055101,766.289465,688.015464,665.203937,811.300526,828.214031,684.884584,604.052823,576.227492,826.414571,...,7.412168,7.718145,8.015059,9.030232,9.677650,7.363355,7.395074,11.699704,11.684008,5.433792
VP_015,669.244617,685.479783,560.162654,530.191686,685.811782,628.429276,598.683391,512.636127,502.825056,629.963332,...,4.539327,5.246841,6.694183,5.970138,5.153506,4.913248,6.128389,7.845547,4.423115,7.218205
VP_016,1046.453462,970.122132,714.018828,792.836185,1086.566596,869.526501,665.445243,507.634943,502.888223,966.393008,...,3.980632,6.409082,12.124605,10.016414,4.702683,6.849862,8.943141,12.115658,7.665027,6.428170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VP_105,741.588732,733.664773,696.053890,699.313256,718.358420,741.053427,698.664608,632.692199,616.490931,730.688955,...,5.105657,5.231419,7.438361,7.173384,6.826087,5.930771,5.966947,9.926151,9.599764,4.983377
VP_106,756.457674,682.610887,655.494888,685.583178,747.165290,742.078993,602.950394,570.143581,657.006836,761.510417,...,9.632391,7.265576,7.846745,7.710195,6.501738,11.820724,11.029433,10.582881,11.269684,6.551911
VP_107,785.352078,725.988307,600.037457,606.745177,792.397357,588.005967,594.194424,487.156384,484.230917,702.987132,...,4.564982,5.553720,8.147325,7.877548,4.922817,7.372233,6.414753,8.091317,7.855973,3.986672
VP_108,692.590784,630.336145,626.935402,631.538878,762.735172,712.180398,682.278047,639.317994,526.171875,768.792503,...,3.769122,4.137316,8.003236,7.448097,4.597293,4.762962,5.982588,6.655507,9.383871,4.234084
VP_109,886.972253,864.215106,764.242788,858.039374,919.687500,863.834447,736.760374,652.822532,720.515951,830.224204,...,6.402470,5.306773,9.717384,5.516417,4.013297,5.383651,7.272666,8.294829,6.300583,5.747945

In [65]:
hr_results_all = hr_results_all.unstack(["condition", "phase"])

In [66]:
# flatten multiindex
hr_results_all.columns = ["_".join(col).strip() for col in hr_results_all.columns.values]

In [67]:
hr_results_all

,HRV_MeanNN_ftsst_Baseline,HRV_MeanNN_ftsst_Prep,HRV_MeanNN_ftsst_Talk,HRV_MeanNN_ftsst_Math,HRV_MeanNN_ftsst_Recovery,HRV_MeanNN_tsst_Baseline,HRV_MeanNN_tsst_Prep,HRV_MeanNN_tsst_Talk,HRV_MeanNN_tsst_Math,HRV_MeanNN_tsst_Recovery,...,HR_SD_ftsst_Baseline,HR_SD_ftsst_Prep,HR_SD_ftsst_Talk,HR_SD_ftsst_Math,HR_SD_ftsst_Recovery,HR_SD_tsst_Baseline,HR_SD_tsst_Prep,HR_SD_tsst_Talk,HR_SD_tsst_Math,HR_SD_tsst_Recovery
subject,,,,,,,,,,,,,,,,,,,,,
VP_009,898.486126,824.761285,618.233945,600.116986,933.919271,NaN,NaN,NaN,NaN,NaN,...,5.089042,7.829233,8.406008,10.975796,5.433539,NaN,NaN,NaN,NaN,NaN
VP_010,819.373292,714.104259,625.696569,663.887175,777.546146,NaN,NaN,NaN,NaN,NaN,...,3.682913,5.296122,7.286303,7.222672,3.864387,NaN,NaN,NaN,NaN,NaN
VP_011,824.154006,885.358364,682.090184,644.070688,900.496517,707.786396,759.093238,611.348977,595.156796,802.681872,...,5.714174,5.383550,7.789262,7.002217,5.470638,5.645469,7.024322,8.996232,7.871257,5.805243
VP_012,814.726027,717.689732,706.927190,665.844167,797.494540,753.984375,755.228062,686.560212,707.337307,776.461039,...,3.000240,5.214479,7.163562,8.267183,2.453322,3.376454,5.031209,7.687287,5.068878,3.230596
VP_013,834.055101,766.289465,688.015464,665.203937,811.300526,828.214031,684.884584,604.052823,576.227492,826.414571,...,7.412168,7.718145,8.015059,9.030232,9.677650,7.363355,7.395074,11.699704,11.684008,5.433792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VP_105,741.588732,733.664773,696.053890,699.313256,718.358420,741.053427,698.664608,632.692199,616.490931,730.688955,...,5.105657,5.231419,7.438361,7.173384,6.826087,5.930771,5.966947,9.926151,9.599764,4.983377
VP_106,756.457674,682.610887,655.494888,685.583178,747.165290,742.078993,602.950394,570.143581,657.006836,761.510417,...,9.632391,7.265576,7.846745,7.710195,6.501738,11.820724,11.029433,10.582881,11.269684,6.551911
VP_107,785.352078,725.988307,600.037457,606.745177,792.397357,588.005967,594.194424,487.156384,484.230917,702.987132,...,4.564982,5.553720,8.147325,7.877548,4.922817,7.372233,6.414753,8.091317,7.855973,3.986672
VP_108,692.590784,630.336145,626.935402,631.538878,762.735172,712.180398,682.278047,639.317994,526.171875,768.792503,...,3.769122,4.137316,8.003236,7.448097,4.597293,4.762962,5.982588,6.655507,9.383871,4.234084
VP_109,886.972253,864.215106,764.242788,858.039374,919.687500,863.834447,736.760374,652.822532,720.515951,830.224204,...,6.402470,5.306773,9.717384,5.516417,4.013297,5.383651,7.272666,8.294829,6.300583,5.747945

In [68]:
hr_results_all

,HRV_MeanNN_ftsst_Baseline,HRV_MeanNN_ftsst_Prep,HRV_MeanNN_ftsst_Talk,HRV_MeanNN_ftsst_Math,HRV_MeanNN_ftsst_Recovery,HRV_MeanNN_tsst_Baseline,HRV_MeanNN_tsst_Prep,HRV_MeanNN_tsst_Talk,HRV_MeanNN_tsst_Math,HRV_MeanNN_tsst_Recovery,...,HR_SD_ftsst_Baseline,HR_SD_ftsst_Prep,HR_SD_ftsst_Talk,HR_SD_ftsst_Math,HR_SD_ftsst_Recovery,HR_SD_tsst_Baseline,HR_SD_tsst_Prep,HR_SD_tsst_Talk,HR_SD_tsst_Math,HR_SD_tsst_Recovery
subject,,,,,,,,,,,,,,,,,,,,,
VP_009,898.486126,824.761285,618.233945,600.116986,933.919271,NaN,NaN,NaN,NaN,NaN,...,5.089042,7.829233,8.406008,10.975796,5.433539,NaN,NaN,NaN,NaN,NaN
VP_010,819.373292,714.104259,625.696569,663.887175,777.546146,NaN,NaN,NaN,NaN,NaN,...,3.682913,5.296122,7.286303,7.222672,3.864387,NaN,NaN,NaN,NaN,NaN
VP_011,824.154006,885.358364,682.090184,644.070688,900.496517,707.786396,759.093238,611.348977,595.156796,802.681872,...,5.714174,5.383550,7.789262,7.002217,5.470638,5.645469,7.024322,8.996232,7.871257,5.805243
VP_012,814.726027,717.689732,706.927190,665.844167,797.494540,753.984375,755.228062,686.560212,707.337307,776.461039,...,3.000240,5.214479,7.163562,8.267183,2.453322,3.376454,5.031209,7.687287,5.068878,3.230596
VP_013,834.055101,766.289465,688.015464,665.203937,811.300526,828.214031,684.884584,604.052823,576.227492,826.414571,...,7.412168,7.718145,8.015059,9.030232,9.677650,7.363355,7.395074,11.699704,11.684008,5.433792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VP_105,741.588732,733.664773,696.053890,699.313256,718.358420,741.053427,698.664608,632.692199,616.490931,730.688955,...,5.105657,5.231419,7.438361,7.173384,6.826087,5.930771,5.966947,9.926151,9.599764,4.983377
VP_106,756.457674,682.610887,655.494888,685.583178,747.165290,742.078993,602.950394,570.143581,657.006836,761.510417,...,9.632391,7.265576,7.846745,7.710195,6.501738,11.820724,11.029433,10.582881,11.269684,6.551911
VP_107,785.352078,725.988307,600.037457,606.745177,792.397357,588.005967,594.194424,487.156384,484.230917,702.987132,...,4.564982,5.553720,8.147325,7.877548,4.922817,7.372233,6.414753,8.091317,7.855973,3.986672
VP_108,692.590784,630.336145,626.935402,631.538878,762.735172,712.180398,682.278047,639.317994,526.171875,768.792503,...,3.769122,4.137316,8.003236,7.448097,4.597293,4.762962,5.982588,6.655507,9.383871,4.234084
VP_109,886.972253,864.215106,764.242788,858.039374,919.687500,863.834447,736.760374,652.822532,720.515951,830.224204,...,6.402470,5.306773,9.717384,5.516417,4.013297,5.383651,7.272666,8.294829,6.300583,5.747945

In [69]:
hr_results_all.to_csv("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/ecg/preliminary/nilspod_hr_v_results.csv")