# Saliva Processing

In [142]:
import json
import re
from pathlib import Path

import pandas as pd
import numpy as np
import pingouin as pg

import matplotlib.pyplot as plt
import seaborn as sns

from fau_colors import cmaps
import biopsykit as bp
from biopsykit.io import load_long_format_csv

from empkins_io.datasets.d03.micro_gapvii import MicroBaseDataset

%load_ext autoreload
%autoreload 2
%matplotlib widget

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [143]:
plt.close("all")

palette = sns.color_palette(cmaps.faculties)
sns.set_theme(context="notebook", style="ticks", palette=palette)

plt.rcParams["figure.figsize"] = (10, 5)
plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["mathtext.default"] = "regular"

palette

[(0.0, 0.1843137254901961, 0.4235294117647059),
 (0.4666666666666667, 0.6235294117647059, 0.7098039215686275),
 (1.0, 0.7215686274509804, 0.10980392156862745),
 (0.0, 0.6392156862745098, 0.8784313725490196),
 (0.2627450980392157, 0.6901960784313725, 0.16470588235294117),
 (0.7843137254901961, 0.06274509803921569, 0.1803921568627451)]

In [144]:
deploy_type = "local"

In [145]:
config_dict = json.load(Path("../config.json").open(encoding="utf-8"))

base_path = Path(config_dict[deploy_type]["base_path"])
base_path

PosixPath('/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro')

In [146]:
path_out = base_path.joinpath("data_tabular/saliva/final")

In [147]:
dataset = MicroBaseDataset(base_path)
dataset

MicroBaseDataset [1696 groups/rows]

        subject condition    phase
   0     VP_001      tsst     Prep
   1     VP_001      tsst  Pause_1
   2     VP_001      tsst     Talk
   3     VP_001      tsst  Pause_2
   4     VP_001      tsst  Pause_3
   ...      ...       ...      ...
   1691  VP_110     ftsst  Pause_2
   1692  VP_110     ftsst  Pause_3
   1693  VP_110     ftsst     Math
   1694  VP_110     ftsst  Pause_4
   1695  VP_110     ftsst  Pause_5

   [1696 rows x 3 columns]

## Cortisol

### Samples

In [148]:
cort_data_1_0 = bp.io.saliva.load_saliva_plate(
    base_path.joinpath("data_tabular/saliva/raw/cortisol_micro_1_0.xlsx"), saliva_type="cortisol", regex_str=r"EmpD03micro (VP_\d+)_(T\d)_(S\d)"
) # EmpD03micro VP_01_T1_S0

FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/saliva/raw/cortisol_micro_1_0.xlsx'

In [ ]:
cort_data_1_1 = bp.io.saliva.load_saliva_plate(
    base_path.joinpath("data_tabular/saliva/raw/cortisol_micro_1_1.xlsx"), saliva_type="cortisol", regex_str=r"EmpD03micro_(VP_\d+)_(D\d)_(S\d)"
) # EmpD03micro_VP_50_D1_S0

In [ ]:
cort_data_1_1

                    cortisol
subject day sample
VP_50   D1  S0       7.45825
            S1           NaN
            S2      24.93900
            S3      26.34850
            S4      17.86050
...                      ...
VP_66   D2  S3           NaN
            S4           NaN
            S5           NaN
            S6           NaN
            S7           NaN

[960 rows x 1 columns]

In [ ]:
cort_data = pd.concat([cort_data_1_0, cort_data_1_1])

In [ ]:
cort_data = cort_data.reset_index().replace({"D1": "T1", "D2" : "T2"})

# add zeros to get 3 digits
cort_data["subject"] = "VP_" + cort_data["subject"].str.split("_").str[1].str.zfill(3)

# drop na in subject
#cort_data = cort_data.dropna(subset=["subject"])

In [ ]:
cort_data.set_index(["subject", "day", "sample"], inplace=True)

In [ ]:
cort_data = cort_data.join(dataset.condition_day_mapping).reset_index()
cort_data = cort_data.drop(columns="day").set_index(["subject", "condition", "sample"])
cort_data

                          cortisol
subject condition sample
VP_001  ftsst     S0       6.40005
                  S1       3.05140
                  S2       5.56030
                  S3           NaN
                  S4       5.24075
...                            ...
VP_110  tsst      S3       8.04905
                  S4       6.66550
                  S5       5.70615
                  S6       3.97445
                  S7       2.96520

[1648 rows x 1 columns]

In [ ]:
# long to wide
cort_data = cort_data.pivot_table(index=["subject"], columns=["condition","sample"], values="cortisol")

In [ ]:
# squeeze multiindex
cort_data.columns = [f"{col[1]}_{col[0]}" for col in cort_data.columns]

In [ ]:
# add cort prefix
cort_data = cort_data.add_prefix("cort_")

In [ ]:
cort_data

,cort_S0_ftsst,cort_S1_ftsst,cort_S2_ftsst,cort_S3_ftsst,cort_S4_ftsst,cort_S5_ftsst,cort_S6_ftsst,cort_S7_ftsst,cort_S0_tsst,cort_S1_tsst,cort_S2_tsst,cort_S3_tsst,cort_S4_tsst,cort_S5_tsst,cort_S6_tsst,cort_S7_tsst
subject,,,,,,,,,,,,,,,,
VP_001,6.40005,3.05140,5.56030,NaN,5.24075,5.41070,3.70475,NaN,NaN,NaN,12.69500,11.94800,9.39420,8.17155,6.66075,5.38295
VP_002,2.05385,1.61020,3.28940,5.94925,5.45100,3.64790,2.68990,1.93830,7.24730,4.607750,5.82180,6.65435,5.51490,4.52785,3.84310,3.10430
VP_003,4.36585,4.77315,12.90150,17.80600,11.20100,11.83100,6.73905,4.52550,10.13500,7.690100,15.81050,17.61150,12.60600,7.33555,4.87360,5.29215
VP_004,2.87840,3.61155,4.13670,4.23975,3.76030,3.13215,2.48405,2.02040,1.45365,2.735700,4.62120,6.91265,6.37045,4.53205,3.02545,2.76285
VP_006,1.24805,1.06825,1.83380,3.63515,2.40665,2.45005,1.61380,1.49385,1.07815,0.940925,4.30530,5.68040,5.86710,3.94365,3.47600,3.03780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VP_106,4.54665,4.43140,4.27075,4.50425,3.57915,2.80490,2.40565,2.33415,10.22750,6.252600,14.83600,13.73100,11.59950,8.53230,6.85770,5.12370
VP_107,1.27460,1.18030,1.58300,2.00190,1.82285,1.59225,1.48885,1.28555,1.29735,1.192000,2.47570,4.25610,3.67670,2.77025,2.25370,1.94310
VP_108,5.21510,4.50310,7.44020,7.83270,7.52170,5.82305,5.13070,4.01805,3.70315,2.958100,4.84445,8.58265,9.46200,6.41035,4.96875,4.55990
VP_109,2.11810,1.64910,1.34995,1.40225,1.18590,1.24235,1.09375,1.05145,2.98185,2.672200,7.27785,10.92800,8.78275,5.48440,4.58725,4.13890
VP_110,6.61890,6.75935,4.90270,5.83080,4.43380,3.40110,2.90165,2.42370,2.42840,4.397000,6.85505,8.04905,6.66550,5.70615,3.97445,2.96520

In [ ]:
# export
cort_data.to_csv(path_out.joinpath("cortisol.csv"))

### Features

In [ ]:
cort_auc = bp.saliva.auc(cort_data, remove_s0=True, sample_times=dataset.sample_times_saliva, saliva_type="cortisol")

In [ ]:
cort_max_inc = bp.saliva.max_increase(cort_data, remove_s0=True, saliva_type="cortisol")
cort_max_inc_percent = bp.saliva.max_increase(cort_data, remove_s0=True, percent=True, saliva_type="cortisol")

In [ ]:
cort_slope = bp.saliva.slope(
    cort_data, sample_labels=["S1", "S4"], sample_times=dataset.sample_times_saliva, saliva_type="cortisol"
)

In [ ]:
cort_features = pd.concat([cort_auc, cort_max_inc, cort_max_inc_percent, cort_slope], axis=1)
cort_features = bp.saliva.utils.saliva_feature_wide_to_long(cort_features, saliva_type="cortisol")
cort_features.head()

                                    cortisol
subject condition saliva_feature
VP_001  ftsst     auc_g                  NaN
                  auc_i                  NaN
                  max_inc           2.508900
                  max_inc_percent  82.221275
                  slopeS1S4         0.060815

In [ ]:
# long to wide 
cort_features = cort_features.pivot_table(index=["subject"], columns=["condition","saliva_feature"], values="cortisol")

In [ ]:
# squeeze multiindex
cort_features.columns = [f"{col[1]}_{col[0]}" for col in cort_features.columns]

In [ ]:
# add cort_feat prefix
cort_features = cort_features.add_prefix("cort_feat_")

In [ ]:
cort_features

,cort_feat_auc_g_ftsst,cort_feat_auc_i_ftsst,cort_feat_max_inc_ftsst,cort_feat_max_inc_percent_ftsst,cort_feat_slopeS1S4_ftsst,cort_feat_auc_g_tsst,cort_feat_auc_i_tsst,cort_feat_max_inc_tsst,cort_feat_max_inc_percent_tsst,cort_feat_slopeS1S4_tsst
subject,,,,,,,,,,
VP_001,NaN,NaN,2.50890,82.221275,0.060815,NaN,NaN,NaN,NaN,NaN
VP_002,267.961275,145.586075,4.33905,269.472736,0.106689,370.741475,20.552475,2.046600,44.416472,0.025199
VP_003,772.372775,409.613375,13.03285,273.045054,0.178551,768.761100,184.313500,9.921400,129.015227,0.136553
VP_004,253.921525,-20.556275,0.62820,17.394194,0.004132,335.457475,127.544275,4.176950,152.683043,0.100965
VP_006,157.556450,76.369450,2.56690,240.290194,0.037178,300.820688,229.310387,4.926175,523.545979,0.136838
...,...,...,...,...,...,...,...,...,...,...
VP_106,260.420650,-76.365750,0.07285,1.643950,-0.023674,740.401600,265.204000,8.583400,137.277293,0.148525
VP_107,119.735600,30.032800,0.82160,69.609421,0.017849,202.522925,111.930925,3.064100,257.055369,0.069019
VP_108,464.510600,122.275000,3.32960,73.940175,0.083850,453.136750,228.321150,6.503900,219.867483,0.180664
VP_109,96.568575,-28.763025,-0.24685,-14.968771,-0.012867,477.374750,274.287550,8.255800,308.951426,0.169737
VP_110,325.136425,-188.574175,-0.92855,-13.737268,-0.064599,422.793750,88.621750,3.652050,83.057767,0.063014

In [ ]:
cort_features.to_csv(path_out.joinpath("cortisol_features.csv"))

## Amylase

### Samples

In [242]:
amy_data_1_0 = bp.io.saliva.load_saliva_plate(
    base_path.joinpath("data_tabular/saliva/cleaned/amylase_micro_1_0.xlsx"), saliva_type="amylase", regex_str=r"(VP\d+) (T\d) (S\d)"
) #  VP01 T1 S0

amy_data_1_1 = bp.io.saliva.load_saliva_plate(base_path.joinpath("data_tabular/saliva/cleaned/amylase_micro_1_1.xlsx"), saliva_type="amylase", regex_str=r"EmpD03micro_(VP_\d+)_(D\d)_(S\d)", check_num_samples = False) # EmpD03micro_VP_50_D1_S0

In [243]:
# split subject between VP and number using regex
amy_data_1_0.reset_index(inplace=True)
amy_data_1_0["subject"] = amy_data_1_0["subject"].str.replace("VP", "VP_")
amy_data_1_0.set_index(["subject", "day", "sample"], inplace=True)

In [244]:
amy_data = pd.concat([amy_data_1_0, amy_data_1_1])

In [245]:
amy_data

                       amylase
subject day sample
VP_01   T1  S0       38.461913
            S1       83.337610
            S2      233.162354
            S3             NaN
            S4       95.635027
...                        ...
VP_110  D2  S3      145.640811
            S4      173.765603
            S5      143.769723
            S6      174.408789
            S7      170.561365

[1624 rows x 1 columns]

In [246]:
amy_data = amy_data.reset_index().replace({"D1": "T1", "D2" : "T2"})

# add zeros to get 3 digits
amy_data["subject"] = "VP_" + amy_data["subject"].str.split("_").str[1].str.zfill(3)

# dropna in level subject
amy_data = amy_data.dropna(subset=["subject"])

amy_data.set_index(["subject", "day", "sample"], inplace=True)

In [247]:
amy_data = amy_data.join(dataset.condition_day_mapping).reset_index()
amy_data = amy_data.drop(columns="day").set_index(["subject", "condition", "sample"])
amy_data

                             amylase
subject condition sample
VP_001  ftsst     S0       38.461913
                  S1       83.337610
                  S2      233.162354
                  S3             NaN
                  S4       95.635027
...                              ...
VP_110  tsst      S3      145.640811
                  S4      173.765603
                  S5      143.769723
                  S6      174.408789
                  S7      170.561365

[1623 rows x 1 columns]

In [237]:
# long to wide
amy_data = amy_data.pivot_table(index=["subject"], columns=["condition","sample"], values="amylase")

In [238]:
# squeeze multiindex
amy_data.columns = [f"{col[1]}_{col[0]}" for col in amy_data.columns]

In [239]:
# add amy prefix
amy_data = amy_data.add_prefix("amy_")

In [240]:
amy_data

,amy_S0_ftsst,amy_S1_ftsst,amy_S2_ftsst,amy_S3_ftsst,amy_S4_ftsst,amy_S5_ftsst,amy_S6_ftsst,amy_S7_ftsst,amy_S0_tsst,amy_S1_tsst,amy_S2_tsst,amy_S3_tsst,amy_S4_tsst,amy_S5_tsst,amy_S6_tsst,amy_S7_tsst
subject,,,,,,,,,,,,,,,,
VP_001,38.461913,83.337610,233.162354,NaN,95.635027,16.549018,NaN,56.726124,10.218395,NaN,133.805877,93.805488,199.794046,58.794752,NaN,NaN
VP_002,113.181976,193.712906,213.983373,91.476983,131.799621,42.412056,64.491273,95.343964,93.410473,154.939139,209.929280,84.834506,112.922098,41.944276,75.780364,179.170145
VP_003,74.189912,270.751078,185.916572,99.886628,144.180199,61.466295,144.138618,190.864645,92.630449,269.417335,265.039616,102.052968,118.709147,86.251487,57.389811,250.582720
VP_004,142.400945,91.525597,116.082516,72.044747,151.344000,110.860522,75.744962,158.879930,148.821600,98.008790,248.206244,81.039917,157.889732,52.709821,49.645418,108.265160
VP_006,222.893574,106.449543,182.072244,96.212705,146.824950,89.329983,131.227344,123.540021,143.790736,145.060647,128.183436,86.160053,125.837494,87.303942,87.216696,98.665281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VP_106,69.153038,68.585736,103.063845,23.074168,75.150238,59.474160,68.794132,95.596289,103.816389,78.195148,34.397066,124.030889,76.134334,61.361310,114.178346,93.269191
VP_107,87.468810,181.073752,184.384947,154.260017,162.306453,101.720843,231.911018,243.106562,130.942719,143.492844,214.764584,154.792587,191.620950,201.311406,167.690040,215.667637
VP_108,258.699517,268.775481,210.609175,229.299011,246.980117,208.977073,187.204378,205.576861,154.573670,202.278654,298.946702,269.160838,220.243111,207.050286,194.809520,184.778893
VP_109,29.128489,25.716942,59.957084,45.608186,25.966291,30.624582,25.399589,25.490261,21.217327,23.812823,27.632395,25.478927,22.543410,25.206910,22.736089,25.841617
VP_110,133.140996,114.473828,223.847337,168.321863,167.415140,165.465685,205.304843,174.952278,134.402589,147.418345,236.961600,145.640811,173.765603,143.769723,174.408789,170.561365

In [241]:
amy_data.to_csv(path_out.joinpath("amylase.csv"))

### Features

In [248]:
amy_auc = bp.saliva.auc(amy_data, remove_s0=True, sample_times=dataset.sample_times_saliva, saliva_type="amylase")

In [249]:
amy_max_inc = bp.saliva.max_increase(amy_data, remove_s0=True, saliva_type="amylase")
amy_max_inc_percent = bp.saliva.max_increase(amy_data, remove_s0=True, percent=True, saliva_type="amylase")

In [250]:
amy_slope = bp.saliva.slope(
    amy_data, sample_labels=["S1", "S4"], sample_times=dataset.sample_times_saliva, saliva_type="amylase"
)

In [251]:
amy_features = pd.concat([amy_auc, amy_max_inc, amy_max_inc_percent, amy_slope], axis=1)
amy_features = bp.saliva.utils.saliva_feature_wide_to_long(amy_features, saliva_type="amylase")
amy_features.head()

                                      amylase
subject condition saliva_feature
VP_001  ftsst     auc_g                   NaN
                  auc_i                   NaN
                  max_inc          149.824744
                  max_inc_percent  179.780467
                  slopeS1S4          0.341595

In [252]:
# long to wide
amy_features = amy_features.pivot_table(index=["subject"], columns=["condition","saliva_feature"], values="amylase")

In [253]:
# squeeze multiindex
amy_features.columns = [f"{col[1]}_{col[0]}" for col in amy_features.columns]

In [254]:
# add amy_feat prefix
amy_features = amy_features.add_prefix("amy_feat_")

In [255]:
amy_features

,amy_feat_auc_g_ftsst,amy_feat_auc_i_ftsst,amy_feat_max_inc_ftsst,amy_feat_max_inc_percent_ftsst,amy_feat_slopeS1S4_ftsst,amy_feat_auc_g_tsst,amy_feat_auc_i_tsst,amy_feat_max_inc_tsst,amy_feat_max_inc_percent_tsst,amy_feat_slopeS1S4_tsst
subject,,,,,,,,,,
VP_001,NaN,NaN,149.824744,179.780467,0.341595,NaN,NaN,NaN,NaN,NaN
VP_002,8827.970611,-5894.210224,20.270468,10.464180,-1.719813,8985.997099,-2789.377484,54.990141,35.491446,-1.167140
VP_003,11470.917355,-9106.164590,-79.886433,-29.505490,-3.515858,11710.518195,-8765.199274,-4.377719,-1.624884,-4.186339
VP_004,8198.435798,1242.490461,67.354334,73.590707,1.661622,8624.075163,1175.407129,150.197454,153.248963,1.663360
VP_006,9665.615592,1575.450327,75.622701,71.040889,1.121539,8115.834911,-2908.774233,-16.877211,-11.634590,-0.533976
...,...,...,...,...,...,...,...,...,...,...
VP_106,5385.826871,173.310967,34.478109,50.270088,0.182347,6230.667907,287.836642,45.835741,58.617116,-0.057245
VP_107,13598.140908,-163.464213,62.032811,34.258312,-0.521314,14047.618290,3142.162160,72.174793,50.298532,1.336892
VP_108,16632.758182,-3794.178357,-21.795363,-8.109134,-0.605427,17261.247832,1888.070114,96.668047,47.789544,0.499013
VP_109,2645.954859,691.467257,34.240142,133.142353,0.006926,1879.053884,69.279334,3.819572,16.039981,-0.035261
VP_110,13616.287810,4916.276887,109.373509,95.544554,1.470592,13147.264086,1943.469860,89.543255,60.740917,0.731868

In [256]:
amy_features.to_csv(path_out.joinpath("amylase_features.csv"))

## Progesterone

In [67]:
prog_estr_data = pd.read_excel(
    base_path.joinpath("data_tabular/saliva/raw/estradiol_progesterone_values.xlsx"), sheet_name=["progesterone", "estradiol"]
)

prog_estr_data = {key: value[["sample ID", key]].dropna() for key, value in prog_estr_data.items()}
prog_estr_data = {
    key: data.assign(**{"subject": prog_estr_data[key]["sample ID"].astype(int).apply(lambda s: f"VP_{s:02d}")})
    for key, data in prog_estr_data.items()
}
prog_estr_data = {key: data.drop(columns="sample ID").set_index("subject") for key, data in prog_estr_data.items()}

prog_estr_data = pd.concat({key: val[key] for key, val in prog_estr_data.items()}, axis=1)
prog_estr_data.head()

         progesterone  estradiol
subject
VP_01         6.82945    8.39855
VP_02         8.65175    1.19390
VP_07        21.09000    6.71075
VP_09        31.98150    7.98360
VP_12        18.00650    5.39575

In [68]:
prog_estr_data.to_csv(path_out.joinpath("progesterone_estradiol.csv"))