In [9]:
from empkins_io.datasets.d03.micro_gapvii import MicroBaseDataset 

import pandas as pd

from pathlib import Path

In [10]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
path_1 = Path("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/extras/raw/condition_list_micro1.0.xlsx")
path_11 = Path("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/extras/raw/condition_list_micro1_1.xlsx")

In [12]:
df1 = pd.read_excel(path_1)
df1 = df1.set_index("subject")["VPN_Kennung"]

# add zero to index
df1.index = "VP_" + df1.index.str.split("_").str[1].str.zfill(3) 

df1

FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/extras/raw/condition_list_micro1.0.xlsx'

In [ ]:
df11 = pd.read_excel(path_11)
df11 = df11.set_index("subject")["VPN_Kennung"]
df11

subject
VP_050    MK31E
VP_051    CG15E
VP_052    MS15N
VP_053    MB20N
VP_054    LG27N
          ...
VP_106    MW11F
VP_107    EN09F
VP_108    UL28M
VP_109    FC25L
VP_110    HV01S
Name: VPN_Kennung, Length: 61, dtype: object

In [ ]:
df_all = pd.concat([df1, df11])
df_all = pd.DataFrame(df_all)
df_all.columns = ["Code"]

In [13]:
#df_all.to_csv("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/extras/processed/id_mapping.csv")

## Condition order

In [16]:
path = Path("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/_extras/processed/condition_order.csv")
condition_order = pd.read_csv(path)

In [17]:
condition_order = condition_order.replace({"TSSTFirst": "tsst_first", "fTSSTFirst": "ftsst_first"})

In [18]:
# save
condition_order.to_csv(path)

## Put PASA together

In [19]:
pasa1 = pd.read_excel(Path("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/questionnaires/raw/PASA_micro_1_0.xlsx"))
pasa11 = pd.read_excel(Path("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/questionnaires/raw/PASA_micro_1_1.xlsx"))

In [20]:
pasa_all = pd.concat([pasa1, pasa11])

In [21]:
pasa_all.rename(columns={"Tag": "day"}, inplace=True)
pasa_all["day"] = "T" + pasa_all["day"].astype(str)

In [22]:
pasa_all["subject"] = "VP_" + pasa_all["subject"].str.split("_").str[1].str.zfill(3)

In [23]:
pasa_all

,subject,VPN_Kennung,day,PASA_01,PASA_02,PASA_03,PASA_04,PASA_05,PASA_06,PASA_07,PASA_08,PASA_09,PASA_10,PASA_11,PASA_12,PASA_13,PASA_14,PASA_15,PASA_16,CG15E
0,VP_001,LI17P,T1,5.0,5.0,4.0,4.0,4.0,2.0,1.0,4.0,4.0,3.0,2.0,4.0,3.0,4.0,2.0,4.0,NaN
1,VP_001,LI17P,T2,3.0,5.0,4.0,4.0,4.0,1.0,1.0,4.0,3.0,2.0,3.0,4.0,4.0,5.0,3.0,4.0,NaN
2,VP_002,IH30R,T1,6.0,4.0,2.0,4.0,4.0,4.0,2.0,3.0,6.0,3.0,2.0,3.0,1.0,4.0,1.0,3.0,NaN
3,VP_002,IH30R,T2,4.0,2.0,4.0,4.0,2.0,2.0,1.0,4.0,4.0,3.0,1.0,5.0,1.0,4.0,1.0,4.0,NaN
4,VP_003,HB25M,T1,3.0,4.0,5.0,5.0,4.0,2.0,1.0,4.0,3.0,3.0,4.0,5.0,4.0,4.0,4.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,VP_108,UL28M,T2,5.0,4.0,6.0,5.0,2.0,2.0,2.0,5.0,4.0,3.0,4.0,3.0,4.0,5.0,5.0,4.0,117.0
118,VP_109,FC25L,T1,6.0,5.0,6.0,4.0,4.0,1.0,1.0,4.0,5.0,4.0,3.0,4.0,4.0,3.0,3.0,5.0,118.0
119,VP_109,FC25L,T2,6.0,3.0,6.0,1.0,1.0,1.0,1.0,4.0,5.0,6.0,2.0,4.0,1.0,1.0,3.0,4.0,119.0
120,VP_110,HV01S,T1,6.0,4.0,3.0,3.0,4.0,3.0,4.0,4.0,3.0,4.0,5.0,2.0,4.0,4.0,4.0,4.0,120.0
121,VP_110,HV01S,T2,3.0,5.0,4.0,NaN,4.0,2.0,4.0,3.0,2.0,2.0,4.0,2.0,3.0,5.0,2.0,4.0,121.0

In [24]:
dataset = MicroBaseDataset(Path("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/"))

In [25]:
# join with condition order
condition_mapping = dataset.condition_day_mapping
condition_mapping

            condition
subject day
VP_001  T1      ftsst
        T2       tsst
VP_002  T1      ftsst
        T2       tsst
VP_003  T1      ftsst
...               ...
VP_108  T2      ftsst
VP_109  T1       tsst
        T2      ftsst
VP_110  T1      ftsst
        T2       tsst

[210 rows x 1 columns]

In [26]:
pasa_all.set_index(["subject", "day"], inplace=True)
pasa_all = pasa_all.join(condition_mapping)

In [27]:
pasa_all = pasa_all.reset_index().set_index(["subject", "condition"])

In [28]:
pasa_all = pasa_all.filter(like="PASA")

In [29]:
# export
pasa_all.to_csv("/Volumes/luca_ssd/Study_Data/2022_12_GAPVII_Micro/data_tabular/questionnaires/processed/pasa.csv")